### ISSUE TITLE
Pace BMS ?

### ISSUE THREAD

**Issue by Starter4711** [pulquero/DCSystemAggregator#2]
Hello, just read inthe solved issue, that a JK BMS with serialbattery is working here?
Sry if I missunderstood, I have 2 Gobel BMS with Heltec BT Balacer, is there a chance to get them over this aggregator into the venus os?
The BMS is connected via VE.Can Bms to the Cerbo, but there are no Cellvoltages. Would like to use the RS232-USB Adapter to get all out of the BMS. (Gobel told me to got that way). Additional the BT Connection to the Heltec?

Thanks a lot.

**Comment by pulquero** [comment]
See https://github.com/pulquero/BatteryAggregator
